---
version: "3"

includes:
  secrets:
    taskfile: ./secrets/Taskfile.yml
    dir: ./secrets

tasks:
  default:
    desc: Liste les commandes disponibles
    silent: true
    cmds:
      - task --list
