package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/resourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/d3nailabs/terraform-provider-coolify/internal/client"
)

var (
	_ resource.Resource                     = (*applicationResource)(nil)
	_ resource.ResourceWithConfigure        = (*applicationResource)(nil)
	_ resource.ResourceWithImportState      = (*applicationResource)(nil)
	_ resource.ResourceWithConfigValidators = (*applicationResource)(nil)
)

// NewApplicationResource is registered in provider.go.
func NewApplicationResource() resource.Resource {
	return &applicationResource{}
}

type applicationResource struct {
	client *client.Client
}

// applicationResourceModel is the union of the five Coolify application kinds.
// The source attributes determine which create endpoint is used; see
// applicationType.
type applicationResourceModel struct {
	UUID types.String `tfsdk:"uuid"`

	// Placement.
	ProjectUUID     types.String `tfsdk:"project_uuid"`
	EnvironmentName types.String `tfsdk:"environment_name"`
	EnvironmentUUID types.String `tfsdk:"environment_uuid"`
	ServerUUID      types.String `tfsdk:"server_uuid"`
	DestinationUUID types.String `tfsdk:"destination_uuid"`

	// Identity.
	Name        types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`

	// Sources.
	GitRepository           types.String `tfsdk:"git_repository"`
	GitBranch               types.String `tfsdk:"git_branch"`
	GitCommitSHA            types.String `tfsdk:"git_commit_sha"`
	PrivateKeyUUID          types.String `tfsdk:"private_key_uuid"`
	GithubAppUUID           types.String `tfsdk:"github_app_uuid"`
	Dockerfile              types.String `tfsdk:"dockerfile"`
	DockerRegistryImageName types.String `tfsdk:"docker_registry_image_name"`
	DockerRegistryImageTag  types.String `tfsdk:"docker_registry_image_tag"`

	// Build & runtime.
	BuildPack              types.String `tfsdk:"build_pack"`
	StaticImage            types.String `tfsdk:"static_image"`
	InstallCommand         types.String `tfsdk:"install_command"`
	BuildCommand           types.String `tfsdk:"build_command"`
	StartCommand           types.String `tfsdk:"start_command"`
	BaseDirectory          types.String `tfsdk:"base_directory"`
	PublishDirectory       types.String `tfsdk:"publish_directory"`
	PortsExposes           types.String `tfsdk:"ports_exposes"`
	PortsMappings          types.String `tfsdk:"ports_mappings"`
	CustomDockerRunOptions types.String `tfsdk:"custom_docker_run_options"`
	PreDeploymentCommand   types.String `tfsdk:"pre_deployment_command"`
	PostDeploymentCommand  types.String `tfsdk:"post_deployment_command"`
	WatchPaths             types.String `tfsdk:"watch_paths"`

	// Domains.
	Domains            types.String `tfsdk:"domains"`
	Redirect           types.String `tfsdk:"redirect"`
	AutogenerateDomain types.Bool   `tfsdk:"autogenerate_domain"`

	// Toggles.
	IsStatic                    types.Bool `tfsdk:"is_static"`
	IsAutoDeployEnabled         types.Bool `tfsdk:"is_auto_deploy_enabled"`
	IsForceHTTPSEnabled         types.Bool `tfsdk:"is_force_https_enabled"`
	IsPreviewDeploymentsEnabled types.Bool `tfsdk:"is_preview_deployments_enabled"`
	InstantDeploy               types.Bool `tfsdk:"instant_deploy"`

	// Health check.
	HealthCheckEnabled types.Bool   `tfsdk:"health_check_enabled"`
	HealthCheckPath    types.String `tfsdk:"health_check_path"`

	// Limits.
	LimitsMemory types.String `tfsdk:"limits_memory"`
	LimitsCPUs   types.String `tfsdk:"limits_cpus"`

	// Read-only.
	Status types.String `tfsdk:"status"`
	FQDN   types.String `tfsdk:"fqdn"`
}

func (r *applicationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application"
}

func (r *applicationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "A Coolify application. The source attributes select how it is built:\n\n" +
			"  * **Public git repository** — set `git_repository` + `git_branch` + `build_pack`.\n" +
			"  * **Private repository (deploy key)** — additionally set `private_key_uuid`.\n" +
			"  * **Private repository (GitHub App)** — additionally set `github_app_uuid`.\n" +
			"  * **Inline Dockerfile** — set `dockerfile` (base64).\n" +
			"  * **Registry image** — set `docker_registry_image_name` (+ optional tag).\n",
		Attributes: map[string]schema.Attribute{
			"uuid": schema.StringAttribute{
				MarkdownDescription: "Server-assigned identifier.",
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},

			// Placement.
			"project_uuid": schema.StringAttribute{
				MarkdownDescription: "UUID of the project. Changing it forces replacement.",
				Required:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"environment_name": schema.StringAttribute{
				MarkdownDescription: "Environment name (e.g. `production`). Exactly one of " +
					"`environment_name` or `environment_uuid` must be set. Changing it forces replacement.",
				Optional:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"environment_uuid": schema.StringAttribute{
				MarkdownDescription: "Environment UUID. Changing it forces replacement.",
				Optional:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"server_uuid": schema.StringAttribute{
				MarkdownDescription: "UUID of the server to deploy on. Changing it forces replacement.",
				Required:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"destination_uuid": schema.StringAttribute{
				MarkdownDescription: "Destination (Docker network) UUID. Required when the server " +
					"has several destinations. Changing it forces replacement.",
				Optional:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			// Identity.
			"name": schema.StringAttribute{
				MarkdownDescription: "Application name. Coolify derives one when omitted.",
				Optional:            true,
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Free-form description.",
				Optional:            true,
			},

			// Sources.
			"git_repository": schema.StringAttribute{
				MarkdownDescription: "Git repository URL (public/deploy-key modes) or `org/repo` (GitHub App mode).",
				Optional:            true,
			},
			"git_branch": schema.StringAttribute{
				MarkdownDescription: "Git branch to deploy.",
				Optional:            true,
			},
			"git_commit_sha": schema.StringAttribute{
				MarkdownDescription: "Pin the deployment to a specific commit (defaults to HEAD).",
				Optional:            true,
			},
			"private_key_uuid": schema.StringAttribute{
				MarkdownDescription: "UUID of the deploy key for private repositories. " +
					"Setting it selects the private-deploy-key mode. Changing it forces replacement.",
				Optional:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"github_app_uuid": schema.StringAttribute{
				MarkdownDescription: "UUID of the GitHub App for private repositories. " +
					"Setting it selects the private-github-app mode. Changing it forces replacement.",
				Optional:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"dockerfile": schema.StringAttribute{
				MarkdownDescription: "Base64-encoded Dockerfile content. Setting it selects the " +
					"dockerfile mode (use `base64encode(file(...))`).",
				Optional: true,
			},
			"docker_registry_image_name": schema.StringAttribute{
				MarkdownDescription: "Docker image to run (e.g. `nginx`). Setting it selects the " +
					"docker-image mode.",
				Optional: true,
			},
			"docker_registry_image_tag": schema.StringAttribute{
				MarkdownDescription: "Image tag. Defaults to `latest`.",
				Optional:            true,
			},

			// Build & runtime.
			"build_pack": schema.StringAttribute{
				MarkdownDescription: "Build pack for git-based modes: `nixpacks`, `static`, " +
					"`dockerfile`, `dockercompose` or `railpack`.",
				Optional: true,
				Validators: []validator.String{
					stringvalidator.OneOf("nixpacks", "static", "dockerfile", "dockercompose", "railpack"),
				},
			},
			"static_image": schema.StringAttribute{
				MarkdownDescription: "Image serving static builds (e.g. `nginx:alpine`).",
				Optional:            true,
			},
			"install_command": schema.StringAttribute{
				MarkdownDescription: "Override the install command.",
				Optional:            true,
			},
			"build_command": schema.StringAttribute{
				MarkdownDescription: "Override the build command.",
				Optional:            true,
			},
			"start_command": schema.StringAttribute{
				MarkdownDescription: "Override the start command.",
				Optional:            true,
			},
			"base_directory": schema.StringAttribute{
				MarkdownDescription: "Directory inside the repository to use as build context (monorepos).",
				Optional:            true,
			},
			"publish_directory": schema.StringAttribute{
				MarkdownDescription: "Directory to publish for static builds.",
				Optional:            true,
			},
			"ports_exposes": schema.StringAttribute{
				MarkdownDescription: "Comma-separated container ports to expose, e.g. `\"3000\"`.",
				Optional:            true,
			},
			"ports_mappings": schema.StringAttribute{
				MarkdownDescription: "Comma-separated host:container port mappings, e.g. `\"8080:3000\"`.",
				Optional:            true,
			},
			"custom_docker_run_options": schema.StringAttribute{
				MarkdownDescription: "Extra options appended to `docker run`.",
				Optional:            true,
			},
			"pre_deployment_command": schema.StringAttribute{
				MarkdownDescription: "Command executed before each deployment.",
				Optional:            true,
			},
			"post_deployment_command": schema.StringAttribute{
				MarkdownDescription: "Command executed after each deployment.",
				Optional:            true,
			},
			"watch_paths": schema.StringAttribute{
				MarkdownDescription: "Newline-separated path globs that trigger auto-deploys (monorepos).",
				Optional:            true,
			},

			// Domains.
			"domains": schema.StringAttribute{
				MarkdownDescription: "Comma-separated FQDNs, e.g. `\"https://app.example.com\"`. " +
					"Leave unset with `autogenerate_domain = true` to let Coolify assign one.",
				Optional: true,
			},
			"redirect": schema.StringAttribute{
				MarkdownDescription: "www redirection behaviour: `www`, `non-www` or `both`.",
				Optional:            true,
				Validators:          []validator.String{stringvalidator.OneOf("www", "non-www", "both")},
			},
			"autogenerate_domain": schema.BoolAttribute{
				MarkdownDescription: "Let Coolify generate a domain when `domains` is unset. Defaults to `true`.",
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(true),
			},

			// Toggles.
			"is_static": schema.BoolAttribute{
				MarkdownDescription: "Serve the build output as a static site.",
				Optional:            true,
			},
			"is_auto_deploy_enabled": schema.BoolAttribute{
				MarkdownDescription: "Deploy automatically on git push (webhooks).",
				Optional:            true,
			},
			"is_force_https_enabled": schema.BoolAttribute{
				MarkdownDescription: "Redirect HTTP to HTTPS.",
				Optional:            true,
			},
			"is_preview_deployments_enabled": schema.BoolAttribute{
				MarkdownDescription: "Deploy pull-request previews.",
				Optional:            true,
			},
			"instant_deploy": schema.BoolAttribute{
				MarkdownDescription: "Queue a first deployment right after creation. Defaults to `false`.",
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(false),
			},

			// Health check.
			"health_check_enabled": schema.BoolAttribute{
				MarkdownDescription: "Enable the container health check.",
				Optional:            true,
			},
			"health_check_path": schema.StringAttribute{
				MarkdownDescription: "HTTP path probed by the health check (e.g. `/health`).",
				Optional:            true,
			},

			// Limits.
			"limits_memory": schema.StringAttribute{
				MarkdownDescription: "Memory limit (e.g. `512m`, `1g`).",
				Optional:            true,
			},
			"limits_cpus": schema.StringAttribute{
				MarkdownDescription: "CPU limit (e.g. `0.5`, `2`).",
				Optional:            true,
			},

			// Read-only.
			"status": schema.StringAttribute{
				MarkdownDescription: "Runtime status reported by Coolify (e.g. `running:healthy`).",
				Computed:            true,
			},
			"fqdn": schema.StringAttribute{
				MarkdownDescription: "Effective domain(s), including any auto-generated one.",
				Computed:            true,
			},
		},
	}
}

// ConfigValidators enforces the mode invariants at plan time so practitioners
// get schema errors instead of API 422s.
func (r *applicationResource) ConfigValidators(_ context.Context) []resource.ConfigValidator {
	return []resource.ConfigValidator{
		// Exactly one environment reference.
		resourcevalidator.ExactlyOneOf(
			path.MatchRoot("environment_name"),
			path.MatchRoot("environment_uuid"),
		),
		// Exactly one source kind.
		resourcevalidator.ExactlyOneOf(
			path.MatchRoot("git_repository"),
			path.MatchRoot("dockerfile"),
			path.MatchRoot("docker_registry_image_name"),
		),
		// Git modes need a branch and a build pack.
		resourcevalidator.RequiredTogether(
			path.MatchRoot("git_repository"),
			path.MatchRoot("git_branch"),
			path.MatchRoot("build_pack"),
		),
		// A deploy key and a GitHub App are mutually exclusive.
		resourcevalidator.Conflicting(
			path.MatchRoot("private_key_uuid"),
			path.MatchRoot("github_app_uuid"),
		),
	}
}

// applicationType derives the Coolify create endpoint from the configuration.
func applicationType(m applicationResourceModel) client.ApplicationType {
	switch {
	case !m.Dockerfile.IsNull():
		return client.ApplicationTypeDockerfile
	case !m.DockerRegistryImageName.IsNull():
		return client.ApplicationTypeDockerImage
	case !m.GithubAppUUID.IsNull():
		return client.ApplicationTypePrivateGithubApp
	case !m.PrivateKeyUUID.IsNull():
		return client.ApplicationTypePrivateDeployKey
	default:
		return client.ApplicationTypePublic
	}
}

func (r *applicationResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = resourceClient(req, resp)
}

// toRequest maps the plan to an API body. create toggles placement fields on.
func applicationToRequest(m applicationResourceModel, create bool) client.ApplicationRequest {
	req := client.ApplicationRequest{
		Name:                        stringOrNil(m.Name),
		Description:                 stringOrNil(m.Description),
		GitRepository:               stringOrNil(m.GitRepository),
		GitBranch:                   stringOrNil(m.GitBranch),
		GitCommitSHA:                stringOrNil(m.GitCommitSHA),
		Dockerfile:                  stringOrNil(m.Dockerfile),
		DockerRegistryImageName:     stringOrNil(m.DockerRegistryImageName),
		DockerRegistryImageTag:      stringOrNil(m.DockerRegistryImageTag),
		BuildPack:                   stringOrNil(m.BuildPack),
		StaticImage:                 stringOrNil(m.StaticImage),
		InstallCommand:              stringOrNil(m.InstallCommand),
		BuildCommand:                stringOrNil(m.BuildCommand),
		StartCommand:                stringOrNil(m.StartCommand),
		BaseDirectory:               stringOrNil(m.BaseDirectory),
		PublishDirectory:            stringOrNil(m.PublishDirectory),
		PortsExposes:                stringOrNil(m.PortsExposes),
		PortsMappings:               stringOrNil(m.PortsMappings),
		CustomDockerRunOptions:      stringOrNil(m.CustomDockerRunOptions),
		PreDeploymentCommand:        stringOrNil(m.PreDeploymentCommand),
		PostDeploymentCommand:       stringOrNil(m.PostDeploymentCommand),
		WatchPaths:                  stringOrNil(m.WatchPaths),
		Domains:                     stringOrNil(m.Domains),
		Redirect:                    stringOrNil(m.Redirect),
		IsStatic:                    boolOrNil(m.IsStatic),
		IsAutoDeployEnabled:         boolOrNil(m.IsAutoDeployEnabled),
		IsForceHTTPSEnabled:         boolOrNil(m.IsForceHTTPSEnabled),
		IsPreviewDeploymentsEnabled: boolOrNil(m.IsPreviewDeploymentsEnabled),
		InstantDeploy:               boolOrNil(m.InstantDeploy),
		HealthCheckEnabled:          boolOrNil(m.HealthCheckEnabled),
		HealthCheckPath:             stringOrNil(m.HealthCheckPath),
		LimitsMemory:                stringOrNil(m.LimitsMemory),
		LimitsCPUs:                  stringOrNil(m.LimitsCPUs),
	}
	if create {
		req.ProjectUUID = stringOrNil(m.ProjectUUID)
		req.EnvironmentName = stringOrNil(m.EnvironmentName)
		req.EnvironmentUUID = stringOrNil(m.EnvironmentUUID)
		req.ServerUUID = stringOrNil(m.ServerUUID)
		req.DestinationUUID = stringOrNil(m.DestinationUUID)
		req.PrivateKeyUUID = stringOrNil(m.PrivateKeyUUID)
		req.GithubAppUUID = stringOrNil(m.GithubAppUUID)
		req.AutogenerateDomain = boolOrNil(m.AutogenerateDomain)
	}
	return req
}

func (r *applicationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan applicationResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	appType := applicationType(plan)
	app, err := r.client.CreateApplication(ctx, appType, applicationToRequest(plan, true))
	if err != nil {
		resp.Diagnostics.AddError(
			fmt.Sprintf("Unable to create Coolify application (%s mode)", appType),
			err.Error(),
		)
		return
	}

	tflog.Trace(ctx, "created application", map[string]any{"uuid": app.UUID, "type": string(appType)})

	resp.Diagnostics.Append(resp.State.Set(ctx, applicationToModel(app, plan))...)
}

func (r *applicationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state applicationResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	app, err := r.client.GetApplication(ctx, state.UUID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			fmt.Sprintf("Unable to read Coolify application %s", state.UUID.ValueString()),
			err.Error(),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, applicationToModel(app, state))...)
}

func (r *applicationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan applicationResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	app, err := r.client.UpdateApplication(ctx, plan.UUID.ValueString(), applicationToRequest(plan, false))
	if err != nil {
		resp.Diagnostics.AddError(
			fmt.Sprintf("Unable to update Coolify application %s", plan.UUID.ValueString()),
			err.Error(),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, applicationToModel(app, plan))...)
}

func (r *applicationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state applicationResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteApplication(ctx, state.UUID.ValueString(), nil, nil, nil, nil)
	if err != nil && !client.IsNotFound(err) {
		resp.Diagnostics.AddError(
			fmt.Sprintf("Unable to delete Coolify application %s", state.UUID.ValueString()),
			err.Error(),
		)
	}
}

func (r *applicationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("uuid"), req, resp)
}

// applicationToModel merges the API object with prior state. Placement and
// source-mode attributes are not echoed usably by the API, so the configured
// values are preserved; free-form strings preserve null-vs-empty.
func applicationToModel(a *client.Application, prior applicationResourceModel) applicationResourceModel {
	m := prior
	m.UUID = types.StringValue(a.UUID)
	m.Name = types.StringValue(a.Name)
	m.Status = types.StringValue(a.Status)
	m.FQDN = types.StringValue(a.FQDN)

	// Attributes the API reliably echoes back: adopt the server value while
	// preserving null when both sides agree on "unset".
	m.Description = keepNullIfEmpty(a.Description, prior.Description)
	m.GitBranch = keepNullIfEmpty(a.GitBranch, prior.GitBranch)
	m.GitCommitSHA = keepNullIfEmpty(a.GitCommitSHA, prior.GitCommitSHA)
	m.BuildPack = keepNullIfEmpty(a.BuildPack, prior.BuildPack)
	m.StaticImage = keepNullIfEmpty(a.StaticImage, prior.StaticImage)
	m.InstallCommand = keepNullIfEmpty(a.InstallCommand, prior.InstallCommand)
	m.BuildCommand = keepNullIfEmpty(a.BuildCommand, prior.BuildCommand)
	m.StartCommand = keepNullIfEmpty(a.StartCommand, prior.StartCommand)
	m.BaseDirectory = keepNullIfEmpty(a.BaseDirectory, prior.BaseDirectory)
	m.PublishDirectory = keepNullIfEmpty(a.PublishDirectory, prior.PublishDirectory)
	m.PortsExposes = keepNullIfEmpty(a.PortsExposes, prior.PortsExposes)
	m.PortsMappings = keepNullIfEmpty(a.PortsMappings, prior.PortsMappings)
	m.CustomDockerRunOptions = keepNullIfEmpty(a.CustomDockerRunOptions, prior.CustomDockerRunOptions)
	m.PreDeploymentCommand = keepNullIfEmpty(a.PreDeploymentCommand, prior.PreDeploymentCommand)
	m.PostDeploymentCommand = keepNullIfEmpty(a.PostDeploymentCommand, prior.PostDeploymentCommand)
	m.WatchPaths = keepNullIfEmpty(a.WatchPaths, prior.WatchPaths)
	m.DockerRegistryImageTag = keepNullIfEmpty(a.DockerRegistryImageTag, prior.DockerRegistryImageTag)
	m.LimitsMemory = keepNullIfEmpty(a.LimitsMemory, prior.LimitsMemory)
	m.LimitsCPUs = keepNullIfEmpty(a.LimitsCPUs, prior.LimitsCPUs)

	return m
}
